### ISSUE TITLE
running error when run eval

### ISSUE THREAD

**Issue by lazyfuzzypringle** [sail-sg/sailor-llm#4]
Hi nice work! I was aware that Thai is difficult to optimize so I'm very interested in the perf eval of this work!
When I started to run the code, it gave me this assertion error, you guys know why it happened?

$python run.py configs/eval_sailor.py -w outputs/sailor --num-gpus 2 --max-num-workers 64
03/08 10:47:25 - OpenCompass - WARNING - SlurmRunner is not used, so the partition argument is ignored.
03/08 10:47:25 - OpenCompass - INFO - Partitioned into 12 tasks.
  0%|                                                                               | 0/12 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/opencompass/opencompass-main/run.py", line 357, in <module>
    main()
  File "/home/opencompass/opencompass-main/run.py", line 309, in main
    runner(tasks)
  File "/home/opencompass/opencompass-main/opencompass/runners/base.py", line 39, in __call__
    self.summarize(status)
  File "/home/opencompass/opencompass-main/opencompass/runners/base.py", line 61, in summarize
    for _task, code in status:
  File "/home/.conda/envs/opencompass/lib/python3.10/concurrent/futures/_base.py", line 609, in result_iterator
    yield fs.pop().result()
  File "/home/.conda/envs/opencompass/lib/python3.10/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/home/.conda/envs/opencompass/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/.conda/envs/opencompass/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/opencompass/opencompass-main/opencompass/runners/local.py", line123, in submit
    assert len(gpus) >= num_gpus
AssertionError
  0%|                                                                               | 0/12 [00:00<?, ?it/s]
(opencompass)

My environment was set up as the guideline you gave, and my GPUs are A800 * 2. they work fine. could you help and see how to resolve the error? Much appreciate it!

**Comment by SivilTaram** [comment]
@lazyfuzzypringle Thanks for your interest! It seems that your problem is solved. Feel free to re-open it if you have any follow-up question!
