### ISSUE TITLE
KeyError: 'options_2'

### ISSUE THREAD

**Issue by harveyhuang18** [sail-sg/sailor-llm#7]
Hi,

I encountered almost the same problem with #6. 

Here is the log:
```
11/10 21:34:54 - OpenCompass - INFO - Current exp folder: opencompass_outputs/Qwen1.5-7B/20241110_213454
11/10 21:34:54 - OpenCompass - WARNING - SlurmRunner is not used, so the partition argument is ignored.
Map:  46%|███████████████████████▌                           | 999/2163 [00:00<00:00, 17085.26 examples/s]
Traceback (most recent call last):
  File "/home/miniconda3/envs/sailor/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 3456, in _map_single
    writer.write(example)
  File "/home/miniconda3/envs/sailor/lib/python3.10/site-packages/datasets/arrow_writer.py", line 492, in write
    self.write_examples_on_file()
  File "/home/miniconda3/envs/sailor/lib/python3.10/site-packages/datasets/arrow_writer.py", line 446, in write_examples_on_file
    batch_examples[col] = [
  File "/home/miniconda3/envs/sailor/lib/python3.10/site-packages/datasets/arrow_writer.py", line 447, in <listcomp>
    row[0][col].to_pylist()[0] if isinstance(row[0][col], (pa.Array, pa.ChunkedArray)) else row[0][col]
KeyError: 'options_2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/workspace/MergeLLM-main-2/./opencompass/run.py", line 4, in <module>
    main()
  File "/mnt/workspace/MergeLLM-main-2/opencompass/opencompass/cli/main.py", line 299, in main
    tasks = partitioner(cfg)
  File "/mnt/workspace/MergeLLM-main-2/opencompass/opencompass/partitioners/base.py", line 83, in __call__
    tasks = self.partition(**model_and_dataset_args,
  File "/mnt/workspace/MergeLLM-main-2/opencompass/opencompass/partitioners/num_worker.py", line 69, in partition
    dataset_size = self.get_size(dataset)
  File "/mnt/workspace/MergeLLM-main-2/opencompass/opencompass/partitioners/num_worker.py", line 141, in get_size
    dataset = build_dataset_from_cfg(dataset)
  File "/mnt/workspace/MergeLLM-main-2/opencompass/opencompass/utils/build.py", line 13, in build_dataset_from_cfg
    return LOAD_DATASET.build(dataset_cfg)
  File "/home/miniconda3/envs/sailor/lib/python3.10/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/miniconda3/envs/sailor/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/mnt/workspace/MergeLLM-main-2/opencompass/opencompass/datasets/base.py", line 12, in __init__
    self.dataset = self.load(**kwargs)
  File "/mnt/workspace/MergeLLM-main-2/opencompass/opencompass/datasets/m3exam.py", line 45, in load
    return dataset.map(preprocess)
  File "/home/miniconda3/envs/sailor/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 592, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/miniconda3/envs/sailor/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 557, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/miniconda3/envs/sailor/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 3093, in map
    for rank, done, content in Dataset._map_single(**dataset_kwargs):
  File "/home/miniconda3/envs/sailor/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 3501, in _map_single
    writer.finalize()
  File "/home/miniconda3/envs/sailor/lib/python3.10/site-packages/datasets/arrow_writer.py", line 588, in finalize
    self.write_examples_on_file()
  File "/home/miniconda3/envs/sailor/lib/python3.10/site-packages/datasets/arrow_writer.py", line 446, in write_examples_on_file
    batch_examples[col] = [
  File "/home/miniconda3/envs/sailor/lib/python3.10/site-packages/datasets/arrow_writer.py", line 447, in <listcomp>
    row[0][col].to_pylist()[0] if isinstance(row[0][col], (pa.Array, pa.ChunkedArray)) else row[0][col]
KeyError: 'options_2'
```
Did this occur because of a connection problem with Huggingface?

Looking forward to getting your response. Thanks!

**Comment by SivilTaram** [comment]
@harveyhuang18 Yes this should be due to the lost connection with HuggingFace, which makes the dataset downloading not successful.

**Comment by harveyhuang18** [comment]
I see. Thanks for your reply!
